let laps = {
    eighteen: -1,
    eightyeight: -1,
    eightythree: -1,
    fifteen: -1,
    fiftyfive: -1,
    fiftyfour: -1,
    five: -1,
    fourteen: -1,
    fourtyeight: -1,
    fourtyone: -1,
    fourtyseven: -1,
    fourtysix: -1,
    fourtythree: -1,
    fourtytwo: -1,
    nine: -1,
    nineteen: -1,
    ninetyfive: -1,
    ninetynine: -1,
    seventeen: -1,
    sixteen: -1,
    sixtytwo: -1,
    ten: -1,
    thirtyeight: -1,
    thirtyfour: -1,
    thirtysix: -1,
    thirtythree: -1,
    thirtytwo: -1,
    three: -1,
    twenty: -1,
    twentyfive: -1,
    twentyfour: -1,
    twentyone: -1,
    twentyseven: -1,
    twentythree: -1,
    two: -1
}
let currentDraft = {
}
let tires = {
    eighteen: 100,
    eightyeight: 100,
    eightythree: 100,
    fifteen: 100,
    fiftyfive: 100,
    fiftyfour: 100,
    five: 100,
    fourteen: 100,
    fourtyeight: 100,
    fourtyone: 100,
    fourtyseven: 100,
    fourtysix: 100,
    fourtythree: 100,
    fourtytwo: 100,
    nine: 100,
    nineteen: 100,
    ninetyfive: 100,
    ninetynine: 100,
    seventeen: 100,
    sixteen: 100,
    sixtytwo: 100,
    ten: 100,
    thirtyeight: 100,
    thirtyfour: 100,
    thirtysix: 100,
    thirtythree: 100,
    thirtytwo: 100,
    three: 100,
    twenty: 100,
    twentyfive: 100,
    twentyfour: 100,
    twentyone: 100,
    twentyseven: 100,
    twentythree: 100,
    two: 100
}
let bodyDamage = {
    eighteen: 100,
    eightyeight: 100,
    eightythree: 100,
    fifteen: 100,
    fiftyfive: 100,
    fiftyfour: 100,
    five: 100,
    fourteen: 100,
    fourtyeight: 100,
    fourtyone: 100,
    fourtyseven: 100,
    fourtysix: 100,
    fourtythree: 100,
    fourtytwo: 100,
    nine: 100,
    nineteen: 100,
    ninetyfive: 100,
    ninetynine: 100,
    seventeen: 100,
    sixteen: 100,
    sixtytwo: 100,
    ten: 100,
    thirtyeight: 100,
    thirtyfour: 100,
    thirtysix: 100,
    thirtythree: 100,
    thirtytwo: 100,
    three: 100,
    twenty: 100,
    twentyfive: 100,
    twentyfour: 100,
    twentyone: 100,
    twentyseven: 100,
    twentythree: 100,
    two: 100
}
let fuel = {
    eighteen: 100,
    eightyeight: 100,
    eightythree: 100,
    fifteen: 100,
    fiftyfive: 100,
    fiftyfour: 100,
    five: 100,
    fourteen: 100,
    fourtyeight: 100,
    fourtyone: 100,
    fourtyseven: 100,
    fourtysix: 100,
    fourtythree: 100,
    fourtytwo: 100,
    nine: 100,
    nineteen: 100,
    ninetyfive: 100,
    ninetynine: 100,
    seventeen: 100,
    sixteen: 100,
    sixtytwo: 100,
    ten: 100,
    thirtyeight: 100,
    thirtyfour: 100,
    thirtysix: 100,
    thirtythree: 100,
    thirtytwo: 100,
    three: 100,
    twenty: 100,
    twentyfive: 100,
    twentyfour: 100,
    twentyone: 100,
    twentyseven: 100,
    twentythree: 100,
    two: 100
}
let lostSpaces = {
    eighteen: 0,
    eightyeight: 0,
    eightythree: 0,
    fifteen: 0,
    fiftyfive: 0,
    fiftyfour: 0,
    five: 0,
    fourteen: 0,
    fourtyeight: 0,
    fourtyone: 0,
    fourtyseven: 0,
    fourtysix: 0,
    fourtythree: 0,
    fourtytwo: 0,
    nine: 0,
    nineteen: 0,
    ninetyfive: 0,
    ninetynine: 0,
    seventeen: 0,
    sixteen: 0,
    sixtytwo: 0,
    ten: 0,
    thirtyeight: 0,
    thirtyfour: 0,
    thirtysix: 0,
    thirtythree: 0,
    thirtytwo: 0,
    three: 0,
    twenty: 0,
    twentyfive: 0,
    twentyfour: 0,
    twentyone: 0,
    twentyseven: 0,
    twentythree: 0,
    two: 0
}
let totalRoundsInPit = {
    eighteen: 0,
    eightyeight: 0,
    eightythree: 0,
    fifteen: 0,
    fiftyfive: 0,
    fiftyfour: 0,
    five: 0,
    fourteen: 0,
    fourtyeight: 0,
    fourtyone: 0,
    fourtyseven: 0,
    fourtysix: 0,
    fourtythree: 0,
    fourtytwo: 0,
    nine: 0,
    nineteen: 0,
    ninetyfive: 0,
    ninetynine: 0,
    seventeen: 0,
    sixteen: 0,
    sixtytwo: 0,
    ten: 0,
    thirtyeight: 0,
    thirtyfour: 0,
    thirtysix: 0,
    thirtythree: 0,
    thirtytwo: 0,
    three: 0,
    twenty: 0,
    twentyfive: 0,
    twentyfour: 0,
    twentyone: 0,
    twentyseven: 0,
    twentythree: 0,
    two: 0
}
let lapsLed = {
    eighteen: 0,
    eightyeight: 0,
    eightythree: 0,
    fifteen: 0,
    fiftyfive: 0,
    fiftyfour: 0,
    five: 0,
    fourteen: 0,
    fourtyeight: 0,
    fourtyone: 0,
    fourtyseven: 0,
    fourtysix: 0,
    fourtythree: 0,
    fourtytwo: 0,
    nine: 0,
    nineteen: 0,
    ninetyfive: 0,
    ninetynine: 0,
    seventeen: 0,
    sixteen: 0,
    sixtytwo: 0,
    ten: 0,
    thirtyeight: 0,
    thirtyfour: 0,
    thirtysix: 0,
    thirtythree: 0,
    thirtytwo: 0,
    three: 0,
    twenty: 0,
    twentyfive: 0,
    twentyfour: 0,
    twentyone: 0,
    twentyseven: 0,
    twentythree: 0,
    two: 0
}

let toPitCars = [];

let startPosition = {
    eighteen: 0,
    eightyeight: 0,
    eightythree: 0,
    five: 0,
    fourteen: 0,
    fourtyeight: 0,
    fourtyone: 0,
    fourtythree: 0,
    fourtytwo: 0,
    nine: 0,
    ninetyfive: 0,
    ninetynine: 0,
    seventeen: 0,
    sixteen: 0,
    sixtytwo: 0,
    ten: 0,
    thirtyeight: 0,
    thirtytwo: 0,
    three: 0,
    twentyfive: 0,
    twentyfour: 0,
    twentyone: 0,
    twentyseven: 0,
    twentythree: 0,
    two: 0
}
let currentPosition = {
    eighteen: 0,
    eightyeight: 0,
    eightythree: 0,
    five: 0,
    fourteen: 0,
    fourtyeight: 0,
    fourtyone: 0,
    fourtythree: 0,
    fourtytwo: 0,
    nine: 0,
    ninetyfive: 0,
    ninetynine: 0,
    seventeen: 0,
    sixteen: 0,
    sixtytwo: 0,
    ten: 0,
    thirtyeight: 0,
    thirtytwo: 0,
    three: 0,
    twentyfive: 0,
    twentyfour: 0,
    twentyone: 0,
    twentyseven: 0,
    twentythree: 0,
    two: 0
}

let positionAfter = {
    round1: {
        eighteen: 0,
        eightyeight: 0,
        eightythree: 0,
        five: 0,
        fourteen: 0,
        fourtyeight: 0,
        fourtyone: 0,
        fourtythree: 0,
        fourtytwo: 0,
        nine: 0,
        ninetyfive: 0,
        ninetynine: 0,
        seventeen: 0,
        sixteen: 0,
        sixtytwo: 0,
        ten: 0,
        thirtyeight: 0,
        thirtytwo: 0,
        three: 0,
        twentyfive: 0,
        twentyfour: 0,
        twentyone: 0,
        twentyseven: 0,
        twentythree: 0,
        two: 0
    },
    round2: {
        eighteen: 0,
        eightyeight: 0,
        eightythree: 0,
        five: 0,
        fourteen: 0,
        fourtyeight: 0,
        fourtyone: 0,
        fourtythree: 0,
        fourtytwo: 0,
        nine: 0,
        ninetyfive: 0,
        ninetynine: 0,
        seventeen: 0,
        sixteen: 0,
        sixtytwo: 0,
        ten: 0,
        thirtyeight: 0,
        thirtytwo: 0,
        three: 0,
        twentyfive: 0,
        twentyfour: 0,
        twentyone: 0,
        twentyseven: 0,
        twentythree: 0,
        two: 0
    },
    round3: {
        eighteen: 0,
        eightyeight: 0,
        eightythree: 0,
        five: 0,
        fourteen: 0,
        fourtyeight: 0,
        fourtyone: 0,
        fourtythree: 0,
        fourtytwo: 0,
        nine: 0,
        ninetyfive: 0,
        ninetynine: 0,
        seventeen: 0,
        sixteen: 0,
        sixtytwo: 0,
        ten: 0,
        thirtyeight: 0,
        thirtytwo: 0,
        three: 0,
        twentyfive: 0,
        twentyfour: 0,
        twentyone: 0,
        twentyseven: 0,
        twentythree: 0,
        two: 0
    },
    round4: {
        eighteen: 0,
        eightyeight: 0,
        eightythree: 0,
        five: 0,
        fourteen: 0,
        fourtyeight: 0,
        fourtyone: 0,
        fourtythree: 0,
        fourtytwo: 0,
        nine: 0,
        ninetyfive: 0,
        ninetynine: 0,
        seventeen: 0,
        sixteen: 0,
        sixtytwo: 0,
        ten: 0,
        thirtyeight: 0,
        thirtytwo: 0,
        three: 0,
        twentyfive: 0,
        twentyfour: 0,
        twentyone: 0,
        twentyseven: 0,
        twentythree: 0,
        two: 0
    },
    round5: {
        eighteen: 0,
        eightyeight: 0,
        eightythree: 0,
        five: 0,
        fourteen: 0,
        fourtyeight: 0,
        fourtyone: 0,
        fourtythree: 0,
        fourtytwo: 0,
        nine: 0,
        ninetyfive: 0,
        ninetynine: 0,
        seventeen: 0,
        sixteen: 0,
        sixtytwo: 0,
        ten: 0,
        thirtyeight: 0,
        thirtytwo: 0,
        three: 0,
        twentyfive: 0,
        twentyfour: 0,
        twentyone: 0,
        twentyseven: 0,
        twentythree: 0,
        two: 0
    },
    round6: {
        eighteen: 0,
        eightyeight: 0,
        eightythree: 0,
        five: 0,
        fourteen: 0,
        fourtyeight: 0,
        fourtyone: 0,
        fourtythree: 0,
        fourtytwo: 0,
        nine: 0,
        ninetyfive: 0,
        ninetynine: 0,
        seventeen: 0,
        sixteen: 0,
        sixtytwo: 0,
        ten: 0,
        thirtyeight: 0,
        thirtytwo: 0,
        three: 0,
        twentyfive: 0,
        twentyfour: 0,
        twentyone: 0,
        twentyseven: 0,
        twentythree: 0,
        two: 0
    },
    round7: {
        eighteen: 0,
        eightyeight: 0,
        eightythree: 0,
        five: 0,
        fourteen: 0,
        fourtyeight: 0,
        fourtyone: 0,
        fourtythree: 0,
        fourtytwo: 0,
        nine: 0,
        ninetyfive: 0,
        ninetynine: 0,
        seventeen: 0,
        sixteen: 0,
        sixtytwo: 0,
        ten: 0,
        thirtyeight: 0,
        thirtytwo: 0,
        three: 0,
        twentyfive: 0,
        twentyfour: 0,
        twentyone: 0,
        twentyseven: 0,
        twentythree: 0,
        two: 0
    },
    round8: {
        eighteen: 0,
        eightyeight: 0,
        eightythree: 0,
        five: 0,
        fourteen: 0,
        fourtyeight: 0,
        fourtyone: 0,
        fourtythree: 0,
        fourtytwo: 0,
        nine: 0,
        ninetyfive: 0,
        ninetynine: 0,
        seventeen: 0,
        sixteen: 0,
        sixtytwo: 0,
        ten: 0,
        thirtyeight: 0,
        thirtytwo: 0,
        three: 0,
        twentyfive: 0,
        twentyfour: 0,
        twentyone: 0,
        twentyseven: 0,
        twentythree: 0,
        two: 0
    },
    round9: {
        eighteen: 0,
        eightyeight: 0,
        eightythree: 0,
        five: 0,
        fourteen: 0,
        fourtyeight: 0,
        fourtyone: 0,
        fourtythree: 0,
        fourtytwo: 0,
        nine: 0,
        ninetyfive: 0,
        ninetynine: 0,
        seventeen: 0,
        sixteen: 0,
        sixtytwo: 0,
        ten: 0,
        thirtyeight: 0,
        thirtytwo: 0,
        three: 0,
        twentyfive: 0,
        twentyfour: 0,
        twentyone: 0,
        twentyseven: 0,
        twentythree: 0,
        two: 0
    },
    round10: {
        eighteen: 0,
        eightyeight: 0,
        eightythree: 0,
        five: 0,
        fourteen: 0,
        fourtyeight: 0,
        fourtyone: 0,
        fourtythree: 0,
        fourtytwo: 0,
        nine: 0,
        ninetyfive: 0,
        ninetynine: 0,
        seventeen: 0,
        sixteen: 0,
        sixtytwo: 0,
        ten: 0,
        thirtyeight: 0,
        thirtytwo: 0,
        three: 0,
        twentyfive: 0,
        twentyfour: 0,
        twentyone: 0,
        twentyseven: 0,
        twentythree: 0,
        two: 0
    }
}

let teams = {
    eighteen: "Team 1",
    eightyeight: "Team 2",
    eightythree: "Team 3",
    five: "Team 4",
    fourteen: "Team 3",
    fourtyeight: "Team 1",
    fourtyone: "Team 1",
    fourtythree: "Team 3",
    fourtytwo: "Team 5",
    nine: "Team 4",
    ninetyfive: "Team 2",
    ninetynine: "Team 2",
    seventeen: "Team 5",
    sixteen: "Team 5",
    sixtytwo: "Team 3",
    ten: "Team 2",
    thirtyeight: "Team 2",
    thirtytwo: "Team 4",
    three: "Team 1",
    twentyfive: "Team 4",
    twentyfour: "Team 1",
    twentyone: "Team 5",
    twentyseven: "Team 4",
    twentythree: "Team 3",
    two: "Team 5"
}

let finishedCars = [];

let teamLeaderboard = {
    "Team 1": 0,
    "Team 2": 0,
    "Team 4": 0,
    "Team 5": 0,
    "Team 3": 0
}
let startingTeamLeaderboard = {
    "Team 1": 0,
    "Team 2": 0,
    "Team 4": 0,
    "Team 5": 0,
    "Team 3": 0
}